services:
  mongodb:
    image: mongo:6
    container_name: myplants-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  api:
    build: ./api
    container_name: myplants-api
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://admin:secret@mongodb:27017/myplants?authSource=admin

volumes:
  mongo_data: