services:
  api:
    build: ./api
    image: myplants-api
    container_name: myplants-api
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - myplants-network

networks:
  myplants-network:
    external: true