services:
  mongodb:
    image: mongo:6
    container_name: myplants-mongodb
    # ports:                 <-- REMOVA OU COMENTE ESTAS DUAS LINHAS
    #   - "27017:27017"      <-- PARA FECHAR O ACESSO EXTERNO
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  api:
    build: ./api
    image: myplants-api
    container_name: myplants-api
    ports:
      - "3001:3001" # Mantemos esta aberta para vocÃª acessar a API do seu PC
    depends_on:
      - mongodb
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://admin:secret@myplants-mongodb:27017/myplants?authSource=admin

volumes:
  mongo_data: