services:
  mongodb:
    image: mongo:6.0
    container_name: myplants-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      myplants-network:
        aliases:
          - mongodb

volumes:
  mongo_data:

networks:
  myplants-network:
    name: myplants-network
    driver: bridge