services:
  api:
    build: ./api
    image: myplants-api
    container_name: myplants-api
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=gemini-1.5-pro
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev

  mongodb:
    image: mongo:6.0
    container_name: myplants-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: